---
- name: Install Docker Compose
  hosts: your_server
  become: true

  tasks:
    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
      tags: [packages]

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3
      tags: [packages]
