---
- name: Install Docker
  hosts: your_server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: [packages]

    - name: Install Docker dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      tags: [packages]

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: [packages]

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      tags: [packages]

    - name: Update apt cache
      apt:
        update_cache: yes
      tags: [packages]

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      tags: [packages]

    - name: Install Docker Python package
      apt:
        name: python3-pip
        state: present
      tags: [packages]

    - name: Install Docker Python package
      pip:
        name: docker
        state: present
      tags: [packages]

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      tags: [services]