---
- name: Install Nginx
  hosts: your_server
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: [packages]

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      tags: [packages]

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      tags: [services]
