---
- name: Run multi playbook
  hosts: your_target_hosts

  tasks:
    - name: Install Docker [playbook install docker]
      import_playbook: install_docker.yml

    - name: Install Docker Compose [playbook install docker compose]
      import_playbook: install_docker_compose.yml

    - name: Install Nginx [playbook install_nginx]
      import_playbook: install_nginx.yml